name: 🚀 Continuous Deployment

on:
  workflow_run:
    workflows:
      - 🛠️ Continuous Integration
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  continuous-deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: 📥 Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: 🌍 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
